# Generated by Django 5.1.15 on 2026-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_guest_browsing', models.BooleanField(default=True)),
                ('budget_allocated', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('budget_used', models.DecimalField(decimal_places=2, default=38200, max_digits=12)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
